#!/bin/bash

echo "=========================================="
echo "  SKI CLOCK NEO - Arduino Project"
echo "=========================================="
echo ""
echo "This is an Arduino hardware project (.ino file)."
echo "It cannot run in the browser environment."
echo ""
echo "📋 Project Contents:"
echo "   - ski-clock-neo.ino: Arduino sketch for NeoPixel LED matrix"
echo ""
echo "🔧 Hardware Required:"
echo "   - Arduino board"
echo "   - 16x16 WS2812 NeoPixel LED matrix"
echo "   - Connection to pin 4"
echo ""
echo "📚 Dependencies:"
echo "   - Adafruit_NeoPixel library"
echo ""
echo "💡 To Use This Code:"
echo "   1. Download the .ino file"
echo "   2. Open in Arduino IDE or PlatformIO"
echo "   3. Install Adafruit_NeoPixel library"
echo "   4. Upload to your Arduino board"
echo ""
echo "📖 See README.md for more information"
echo "=========================================="
